{{- if empty .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wanportal.fullname" . }}
  labels:
    {{- include "wanportal.labels" . | nindent 4 }}
type: Opaque
stringData:
  MYSQL_PASSWORD: {{ .Values.secrets.mysqlPassword | quote }}
  JWT_SECRET: {{ .Values.secrets.jwtSecret | quote }}
  APP_SECRET: {{ .Values.secrets.appSecret | quote }}
  {{- if .Values.auth.ldap.enabled }}
  AUTH_LDAP_BIND_PASSWORD: {{ .Values.secrets.authLdapBindPassword | quote }}
  {{- end }}
{{- end }}
