<?php
// Constants
define('DEBUG_MODE', false);
define('HOUR_IN_SECONDS', 3600);
define('WARNING_THRESHOLD_HOURS', 3);
define('DANGER_THRESHOLD_HOURS', 5);
define('API_BASE_URL', 'http://localhost/cgi-bin/api');

// ------------------------------------------------------------------
// Session bootstrap
// ------------------------------------------------------------------
// Centralized session_start() that hardens the session cookie.
// Bare session_start() in the page files would use PHP's default
// cookie params (no HttpOnly, no SameSite, no Secure), so every
// page should call wanportal_session_start() instead.
//
// The htdocs/.user.ini file also sets the same options for
// mod_php processes that don't go through this helper, but having
// the logic here too means the settings apply even if the
// .user.ini is missing, has wrong perms, or is cached.
function wanportal_session_start(): void
{
    if (session_status() === PHP_SESSION_ACTIVE) {
        return;
    }

    // Determine if the request is effectively HTTPS. Check both the
    // direct server var (when Apache terminates TLS) and the
    // X-Forwarded-Proto header (when a reverse proxy does it).
    $is_https = (
        (!empty($_SERVER['HTTPS']) && strtolower((string) $_SERVER['HTTPS']) !== 'off')
        || (isset($_SERVER['HTTP_X_FORWARDED_PROTO'])
            && strtolower((string) $_SERVER['HTTP_X_FORWARDED_PROTO']) === 'https')
    );

    ini_set('session.cookie_httponly', '1');
    ini_set('session.cookie_samesite', 'Lax');
    ini_set('session.use_strict_mode', '1');
    if ($is_https) {
        ini_set('session.cookie_secure', '1');
    }

    session_start();
}

// lib/monitor_metrics.php is auto-loaded so all the *_edit / list
// pages can call monitor_color_classes() without an extra require.
// The file defines exactly one function and is safe to include
// unconditionally.
require_once __DIR__ . '/lib/monitor_metrics.php';

/**
 * Verify the CSRF token from a form POST.
 *
 * Compares $_POST['csrf_token'] against $_SESSION['csrf_token']
 * using hash_equals (constant-time). Returns true on match, false
 * on any mismatch (including missing session token, missing POST
 * token, or different values).
 *
 * Use at the top of every POST handler that mutates state:
 *
 *     if ($_SERVER['REQUEST_METHOD'] === 'POST') {
 *         if (!wanportal_csrf_valid()) {
 *             $error = 'Invalid CSRF token. Please reload the page and try again.';
 *         } else {
 *             // ... handle the form
 *         }
 *     }
 *
 * The token is generated by navbar.php and embedded as a hidden
 * field in every <form method="post">. If the form is missing the
 * hidden field (e.g. submitted via curl with no token), the check
 * fails and the handler should refuse to act.
 */
function wanportal_csrf_valid(): bool
{
    $session = $_SESSION['csrf_token'] ?? '';
    $posted  = $_POST['csrf_token']    ?? '';
    if (!is_string($session) || !is_string($posted)) {
        return false;
    }
    if ($session === '' || $posted === '') {
        return false;
    }
    return hash_equals($session, $posted);
}

/**
 * Render a standardized page header (title + breadcrumb + actions).
 *
 * Used at the top of every list/detail page so the visual
 * hierarchy is consistent across the app. Echoes its output
 * directly; don't assign.
 *
 * @param string $title       The page title (h1 text).
 * @param array  $breadcrumbs Optional. Array of [label, url] pairs.
 *                            The first entry is conventionally the
 *                            app root (rendered as a link). The last
 *                            entry is the current page (rendered as
 *                            active text, no link). Omit to render
 *                            just the title with no breadcrumb.
 * @param string $actions     Optional. Raw HTML for the page's
 *                            primary action button(s) (e.g. a
 *                            "New X" link). Rendered to the right
 *                            of the title. Empty string = no actions.
 */
function page_header(string $title, array $breadcrumbs = [], string $actions = ''): void
{
    echo '<div class="page-header mb-4">';
    if (!empty($breadcrumbs)) {
        echo '<nav aria-label="breadcrumb"><ol class="breadcrumb mb-2">';
        $last = count($breadcrumbs) - 1;
        foreach ($breadcrumbs as $i => $crumb) {
            list($label, $url) = $crumb;
            if ($i === $last) {
                // Current page: active text, no link
                echo '<li class="breadcrumb-item active" aria-current="page">'
                    . htmlspecialchars((string) $label, ENT_QUOTES, 'UTF-8')
                    . '</li>';
            } else {
                echo '<li class="breadcrumb-item"><a href="'
                    . htmlspecialchars((string) $url, ENT_QUOTES, 'UTF-8')
                    . '">'
                    . htmlspecialchars((string) $label, ENT_QUOTES, 'UTF-8')
                    . '</a></li>';
            }
        }
        echo '</ol></nav>';
    }
    echo '<div class="d-flex justify-content-between align-items-center">';
    echo '<h1 class="page-title h3 mb-0">'
        . htmlspecialchars($title, ENT_QUOTES, 'UTF-8')
        . '</h1>';
    if ($actions !== '') {
        echo '<div class="page-actions d-flex gap-2">'
            . $actions
            . '</div>';
    }
    echo '</div>';
    echo '</div>';
}

/**
 * Render an empty-state block — used by list pages when there's
 * no data to show. Pairs a friendly icon + message with a primary
 * CTA so the user knows what to do next.
 *
 * @param string $icon   Bootstrap icon class (e.g. "bi-server")
 * @param string $title  Short heading (e.g. "No agents yet")
 * @param string $body   Optional longer description.
 * @param string $cta    Optional. Raw HTML for a primary action
 *                       (typically a "+ New" link). Empty = no CTA.
 */
function empty_state(string $icon, string $title, string $body = '', string $cta = ''): void
{
    echo '<div class="empty-state text-center py-5">';
    echo '<i class="bi ' . htmlspecialchars($icon, ENT_QUOTES, 'UTF-8')
        . ' text-muted" style="font-size: 3rem;"></i>';
    echo '<h3 class="h5 mt-3">'
        . htmlspecialchars($title, ENT_QUOTES, 'UTF-8')
        . '</h3>';
    if ($body !== '') {
        echo '<p class="text-muted">'
            . htmlspecialchars($body, ENT_QUOTES, 'UTF-8')
            . '</p>';
    }
    if ($cta !== '') {
        echo '<div class="mt-3">' . $cta . '</div>';
    }
    echo '</div>';
}

// Database credentials.
// Host/user/db get sensible local-dev defaults; the password does
// NOT — falling back to a known string ('netops') when MYSQL_PASSWORD
// is unset silently accepts that password in production, which is
// the worst kind of credential leak (the operator never notices
// because the connection still works). Fail-closed instead.
$db_host = getenv('MYSQL_HOST') ?: 'localhost';
$db_user = getenv('MYSQL_USER') ?: 'root';
$db_pass = getenv('MYSQL_PASSWORD');
if (!isset($db_pass) || $db_pass === '') {
    die("MYSQL_PASSWORD environment variable is required and must not be empty");
}
// 'netops' is the default in docker-compose.yml (MYSQL_DB=${MYSQL_DB:-netops}).
// Keeping the PHP default aligned with the compose default avoids the
// case where someone deploys the image without setting MYSQL_DB and
// the app silently tries to connect to a non-existent database named
// 'netping'.
$db_name = getenv('MYSQL_DB') ?: 'netops';

// Create mysqli connection
$mysqli = new mysqli($db_host, $db_user, $db_pass, $db_name);
if ($mysqli->connect_errno) {
    die("DB connection failed: " . $mysqli->connect_error);
}

// Menu Structure
$menuItems = [
    'Home' => [
        'url' => '/',
        'icon' => 'bi bi-house-door',
        'auth' => false
    ],
    'Admin' => [
        'type' => 'dropdown',
        'icon' => 'bi bi-shield-lock',
        'auth' => true,
        'items' => [
            'Agents' => [
                'url' => '/agents.php',
                'icon' => 'bi bi-server',
                'auth' => true
            ],
            'Targets' => [
                'url' => '/targets.php',
                'icon' => 'bi bi-bullseye',
                'auth' => true
            ],
            'Monitors' => [
                'url' => '/monitors.php',
                'icon' => 'bi bi-graph-up',
                'auth' => true
            ],
            'Credentials' => [
                'url' => '/credentials.php',
                'icon' => 'bi bi-safe',
                'auth' => true
            ],
            'Users' => [
                'url' => '/users.php',
                'icon' => 'bi bi-people',
                'admin' => true
            ]
        ]
    ],
];
?>
